name: Daily Wallpaper
# Controls when the workflow will run

on:

  # Triggers the workflow on push or pull request events but only for the "main" branch

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]

jobs:
  daily-wallpaper-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Bash Script
        run: bash daily_wallpaper.sh
      - name: Commit Files
        run: |
          git config --global user.email "paddy7594@gmail.com"
          git config --global user.name "Paddy"
          git add wallpaper.txt
          git commit -m "Add today's wallpaper"
          git push origin ${{ github.ref }}
